import React, { useState, useCallback, useEffect, useRef } from "react";
import { FileCode, Globe, ExternalLink, Copy } from "lucide-react";
import { useWorkspace, useUI } from "@/store/useAppStore";
import { useToast } from "@/components/ui/toastStore";
import { basename } from "@/lib/pathUtils";
import { closeIncompleteMarkdown } from "@/lib/chatUtils";
import Markdown from "react-markdown";
import remarkGfm from "remark-gfm";
import hljs from "@/lib/highlight";

const MARKDOWN_REMARK_PLUGINS = [remarkGfm];

// Module-level escapeHtml — stable reference, never recreated per render
function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

// Sanitize highlighted HTML output to prevent XSS via crafted code content.
// Strips event handler attributes and dangerous tags while preserving
// the syntax highlighting spans generated by highlight.js.
function sanitizeHighlightedHtml(html: string): string {
  return (
    html
      // Remove event handler attributes (onclick, onerror, onload, etc.)
      .replace(/\s+on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, "")
      // Remove javascript: protocol in href/src attributes
      .replace(
        /((?:href|src|action)\s*=\s*)(["'])javascript:[^"']*\2/gi,
        "$1$2#",
      )
      // Remove data: protocol in img src (except for small data URIs which are safe)
      .replace(
        /(<img[^>]*?\ssrc\s*=\s*)(["'])data:text\/html/gi,
        "$1$2data:text/plain",
      )
      // Remove <script>, <iframe>, <object>, <embed>, <form> tags
      .replace(/<script\b[^>]*>/gi, "<!-- ")
      .replace(/<\/script\b[^>]*>/gi, " -->")
      .replace(/<iframe\b[^>]*>[\s\S]*?<\/iframe>/gi, "")
      .replace(/<object\b[^>]*>[\s\S]*?<\/object>/gi, "")
      .replace(/<embed\b[^>]*>/gi, "")
      .replace(/<form\b[^>]*>[\s\S]*?<\/form>/gi, "")
  );
}

// Named link component (extracted to satisfy React hooks rules)
function LinkComponent({
  href,
  children,
  ...props
}: React.AnchorHTMLAttributes<HTMLAnchorElement> & {
  children: React.ReactNode;
}) {
  const [showMenu, setShowMenu] = useState(false);
  const menuRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!showMenu) return;
    const close = (e: MouseEvent) => {
      if (menuRef.current && !menuRef.current.contains(e.target as Node))
        setShowMenu(false);
    };
    document.addEventListener("mousedown", close);
    return () => document.removeEventListener("mousedown", close);
  }, [showMenu]);

  const safeUrl = (() => {
    if (!href) return { isExternal: false, safeHref: "#" };
    try {
      const u = new URL(href);
      const safe = u.protocol === "http:" || u.protocol === "https:";
      return { isExternal: safe, safeHref: safe ? u.href : "#" };
    } catch (e) {
      if (import.meta.env.DEV) console.warn("[ChatLink] URL parsing failed:", e);
      // Invalid URL — check for javascript: or other dangerous protocols
      if (
        /^\s*javascript:/i.test(href) ||
        /^\s*data:/i.test(href) ||
        /^\s*vbscript:/i.test(href)
      ) {
        return { isExternal: false, safeHref: "#" };
      }
      return { isExternal: false, safeHref: href };
    }
  })();

  return (
    <span className="relative inline-block">
      <a
        href={safeUrl.safeHref}
        {...props}
        onClick={(e) => {
          e.preventDefault();
          if (safeUrl.isExternal) setShowMenu(!showMenu);
        }}
        className="text-dalam-accent-primary hover:underline cursor-pointer"
      >
        {children}
      </a>
      {showMenu && safeUrl.isExternal && (
        <div
          ref={menuRef}
          className="absolute z-50 bottom-full left-0 mb-1 w-52 bg-dalam-bg-secondary border border-dalam-border-primary rounded-lg shadow-lg py-1 animate-fade-in"
        >
          <button
            className="w-full text-left px-3 py-1.5 text-xs text-dalam-text-primary hover:bg-dalam-bg-hover flex items-center gap-2"
            onClick={() => {
              const ui = useUI.getState();
              ui.addBrowserTab({ url: href! });
              ui.setRightPanelTab("browser");
              if (!ui.rightPanelOpen) ui.setRightPanelOpen(true);
              setShowMenu(false);
            }}
          >
            <Globe className="w-3.5 h-3.5" /> Open in Dalam
          </button>
          <button
            className="w-full text-left px-3 py-1.5 text-xs text-dalam-text-primary hover:bg-dalam-bg-hover flex items-center gap-2"
            onClick={() => {
              try {
                window.open(href, "_blank");
              } catch (e) {
                if (import.meta.env.DEV) console.warn("[ChatLink] window.open failed:", e);
              }
              setShowMenu(false);
            }}
          >
            <ExternalLink className="w-3.5 h-3.5" /> Open in external browser
          </button>
          <button
            className="w-full text-left px-3 py-1.5 text-xs text-dalam-text-primary hover:bg-dalam-bg-hover flex items-center gap-2"
            onClick={() => {
              navigator.clipboard.writeText(href || "").catch(() => {});
              setShowMenu(false);
            }}
          >
            <Copy className="w-3.5 h-3.5" /> Copy URL
          </button>
        </div>
      )}
    </span>
  );
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const MARKDOWN_COMPONENTS: Record<string, any> = {
  p: ({ children }: { children: React.ReactNode }) => (
    <p className="whitespace-pre-wrap break-words mb-2 last:mb-0">{children}</p>
  ),
  strong: ({ children }: { children: React.ReactNode }) => (
    <strong className="font-semibold text-dalam-text-primary">
      {children}
    </strong>
  ),
  em: ({ children }: { children: React.ReactNode }) => (
    <em className="italic">{children}</em>
  ),
  a: LinkComponent,
  ul: ({ children }: { children: React.ReactNode }) => (
    <ul className="list-disc list-inside mb-2 space-y-0.5">{children}</ul>
  ),
  ol: ({ children }: { children: React.ReactNode }) => (
    <ol className="list-decimal list-inside mb-2 space-y-0.5">{children}</ol>
  ),
  li: ({ children }: { children: React.ReactNode }) => (
    <li className="text-dalam-text-secondary">{children}</li>
  ),
  h1: ({ children }: { children: React.ReactNode }) => (
    <h1 className="text-lg font-bold mb-2 text-dalam-text-primary">
      {children}
    </h1>
  ),
  h2: ({ children }: { children: React.ReactNode }) => (
    <h2 className="text-base font-bold mb-2 text-dalam-text-primary">
      {children}
    </h2>
  ),
  h3: ({ children }: { children: React.ReactNode }) => (
    <h3 className="text-sm font-bold mb-1 text-dalam-text-primary">
      {children}
    </h3>
  ),
  code: ({
    children,
    className,
  }: {
    children: React.ReactNode;
    className?: string;
  }) => {
    const isInline = !className;
    if (isInline) {
      return (
        <code className="px-1 py-0.5 bg-dalam-bg-tertiary rounded text-[12px] font-mono text-dalam-accent-primary">
          {children}
        </code>
      );
    }
    return <code className={className}>{children}</code>;
  },
  blockquote: ({ children }: { children: React.ReactNode }) => (
    <blockquote className="border-l-2 border-dalam-accent-primary/40 pl-3 my-2 text-dalam-text-muted italic">
      {children}
    </blockquote>
  ),
  hr: () => <hr className="my-3 border-dalam-border-primary" />,
  table: ({ children }: { children: React.ReactNode }) => (
    <div className="overflow-x-auto my-2">
      <table className="text-xs border-collapse">{children}</table>
    </div>
  ),
  th: ({ children }: { children: React.ReactNode }) => (
    <th className="px-2 py-1 border border-dalam-border-primary text-left font-medium">
      {children}
    </th>
  ),
  td: ({ children }: { children: React.ReactNode }) => (
    <td className="px-2 py-1 border border-dalam-border-primary">{children}</td>
  ),
};

export const MarkdownContent = React.memo(function MarkdownContent({
  content,
}: {
  content: string;
}) {
  return (
    <Markdown
      remarkPlugins={MARKDOWN_REMARK_PLUGINS}
      components={MARKDOWN_COMPONENTS}
    >
      {content}
    </Markdown>
  );
});

// Lightweight streaming renderer — uses full markdown parsing for real-time formatting.
// react-markdown is fast enough for streaming deltas. The visual quality improvement
// (proper bold, headings, lists, code highlighting) far outweighs the minor re-parse cost.
export const StreamingContent = React.memo(function StreamingContent({
  content,
}: {
  content: string;
}) {
  // Close incomplete markdown markers so bold/italic render correctly during streaming
  const safeContent = closeIncompleteMarkdown(content);
  return <MarkdownContent content={safeContent} />;
});

export const CodeBlock = React.memo(function CodeBlock({
  language,
  content,
  filename,
}: {
  language: string;
  content: string;
  filename?: string;
}) {
  const toast = useToast();
  const activeFilePath = useWorkspace((s) => s.activeFilePath);
  const updateTabContent = useWorkspace((s) => s.updateTabContent);
  const [expanded, setExpanded] = useState(true);
  const lines = content.split("\n");
  const isLong = lines.length > 30;

  // Synchronous highlighting via useMemo — guard against large content to prevent frame drops
  const highlighted = React.useMemo(() => {
    if (content.length > 10000) return escapeHtml(content);
    const lang =
      language && hljs.getLanguage(language) ? language : "plaintext";
    try {
      return hljs.highlight(content, { language: lang }).value;
    } catch (e) {
      if (import.meta.env.DEV) console.warn("[CodeBlock] hljs.highlight failed:", e);
      return escapeHtml(content);
    }
  }, [content, language]);

  const handleApply = useCallback(async () => {
    if (!activeFilePath) {
      toast.info("No active file open in the editor");
      return;
    }
    const { openTabs } = useWorkspace.getState();
    const currentTab = openTabs.find((t) => t.path === activeFilePath);
    const hasExistingContent =
      currentTab && currentTab.content.trim().length > 0;
    if (hasExistingContent) {
      let shouldOverwrite;
      try {
        const { confirm } = await import("@tauri-apps/plugin-dialog");
        shouldOverwrite = await confirm(
          `Overwrite entire content of ${basename(activeFilePath)}? This cannot be undone.`,
          { title: "Overwrite file?", kind: "warning" },
        );
      } catch (e) {
        if (import.meta.env.DEV) console.warn("[ApplyButton] Tauri confirm dialog failed, falling back:", e);
        try {
          shouldOverwrite = window.confirm(
            `Overwrite entire content of ${basename(activeFilePath)}? This cannot be undone.`,
          );
        } catch (e2) {
          if (import.meta.env.DEV) console.warn("[ApplyButton] window.confirm also failed:", e2);
          shouldOverwrite = true;
        }
      }
      if (!shouldOverwrite) return;
    }
    updateTabContent(activeFilePath, content);
    toast.success("Applied to editor");
  }, [activeFilePath, content, updateTabContent, toast]);

  return (
    <div className="my-2 bg-dalam-bg-primary border border-dalam-border-primary rounded-lg overflow-hidden">
      <div className="flex items-center justify-between px-3 py-1.5 bg-dalam-bg-tertiary border-b border-dalam-border-primary">
        <div className="flex items-center gap-1.5 text-[10px] text-dalam-text-muted min-w-0">
          <FileCode className="w-3 h-3 shrink-0" />
          {filename ? (
            <span className="font-medium text-dalam-text-secondary truncate" title={filename}>
              {filename}
            </span>
          ) : (
            <span>{language || "code"}</span>
          )}
          <span className="text-dalam-text-muted/50 shrink-0">
            · {lines.length} lines
          </span>
        </div>
        <div className="flex items-center gap-1">
          <button
            className="text-[10px] text-dalam-text-muted hover:text-dalam-text-primary flex items-center gap-1 px-1.5 py-0.5 rounded hover:bg-dalam-bg-hover transition-colors"
            onClick={() => {
              navigator.clipboard.writeText(content).then(
                () => toast.success("Copied to clipboard"),
                () => toast.error("Failed to copy"),
              );
            }}
          >
            Copy
          </button>
          {isLong && (
            <button
              className="text-[10px] text-dalam-text-muted hover:text-dalam-text-primary flex items-center gap-1 px-1.5 py-0.5 rounded hover:bg-dalam-bg-hover transition-colors"
              onClick={() => setExpanded(!expanded)}
            >
              {expanded ? "Collapse" : "Expand"}
            </button>
          )}
          <button
            className="text-[10px] text-dalam-text-muted hover:text-dalam-text-primary flex items-center gap-1 px-1.5 py-0.5 rounded hover:bg-dalam-bg-hover transition-colors"
            onClick={handleApply}
          >
            Apply
          </button>
        </div>
      </div>
      <pre
        className="p-3 text-[12px] font-mono text-dalam-text-primary overflow-x-auto scrollbar-thin leading-relaxed"
        style={{ maxHeight: isLong && !expanded ? "240px" : undefined }}
      >
        <code
          dangerouslySetInnerHTML={{
            __html: sanitizeHighlightedHtml(highlighted),
          }}
        />
      </pre>
      {isLong && !expanded && (
        <button
          className="w-full py-1.5 text-[10px] text-dalam-accent-primary hover:bg-dalam-bg-hover border-t border-dalam-border-primary transition-colors"
          onClick={() => setExpanded(true)}
        >
          Show all {lines.length} lines
        </button>
      )}
    </div>
  );
});

// Streaming code block — shows highlighted code immediately during stream
// For very large blocks (>10000 chars), falls back to plaintext to avoid frame drops.
export const StreamingCodeBlock = React.memo(function StreamingCodeBlock({
  language,
  content,
  filename,
}: {
  language: string;
  content: string;
  filename?: string;
}) {
  const lines = content.split("\n");
  const isLong = lines.length > 30;
  const [expanded, setExpanded] = useState(true);

  // Synchronous highlighting via useMemo — no flash, no 100ms delay
  // Length guard: skip highlight.js for very large blocks during streaming
  // to prevent frame drops from synchronous parsing of huge content.
  // During streaming, skip highlightAuto (very slow) — only use known language if available.
  const highlighted = React.useMemo(() => {
    if (content.length > 10000) return escapeHtml(content);
    if (language && hljs.getLanguage(language)) {
      try {
        return hljs.highlight(content, { language }).value;
      } catch (e) {
        if (import.meta.env.DEV) console.warn("[StreamingCodeBlock] hljs.highlight failed:", e);
      }
    }
    // During streaming, skip highlightAuto — it's too slow for real-time rendering
    return escapeHtml(content);
  }, [content, language]);

  return (
    <div className="my-2 bg-dalam-bg-primary border border-dalam-border-primary rounded-lg overflow-hidden">
      <div className="flex items-center justify-between px-3 py-1.5 bg-dalam-bg-tertiary border-b border-dalam-border-primary">
        <div className="flex items-center gap-1.5 text-[10px] text-dalam-text-muted min-w-0">
          <FileCode className="w-3 h-3 shrink-0" />
          {filename ? (
            <span className="font-medium text-dalam-text-secondary truncate" title={filename}>
              {filename}
            </span>
          ) : (
            <span>{language || "code"}</span>
          )}
          <span className="text-dalam-text-muted/50 shrink-0">
            · {lines.length} lines
          </span>
        </div>
        <div className="flex items-center gap-1">
          {isLong && (
            <button
              className="text-[10px] text-dalam-text-muted hover:text-dalam-text-primary px-1.5 py-0.5 rounded hover:bg-dalam-bg-hover transition-colors"
              onClick={() => setExpanded(!expanded)}
            >
              {expanded ? "Collapse" : "Expand"}
            </button>
          )}
        </div>
      </div>
      <pre
        className="p-3 text-[12px] font-mono text-dalam-text-primary overflow-x-auto scrollbar-thin leading-relaxed"
        style={{ maxHeight: isLong && !expanded ? "240px" : undefined }}
      >
        <code
          dangerouslySetInnerHTML={{
            __html: sanitizeHighlightedHtml(highlighted),
          }}
        />
      </pre>
      {isLong && !expanded && (
        <button
          className="w-full py-1.5 text-[10px] text-dalam-accent-primary hover:bg-dalam-bg-hover border-t border-dalam-border-primary transition-colors"
          onClick={() => setExpanded(true)}
        >
          Show all {lines.length} lines
        </button>
      )}
    </div>
  );
});
